apiVersion: v1
kind: Service
metadata:
  name: aspera-browser
  labels:
    app: aspera-browser
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: aspera-browser

